In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.losses import BinaryCrossentropy
from sklearn.metrics import classification_report

/Users/lionelweng/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Courses/Machine Learning Course/Basics/Lecture 16.csv')

In [ ]:
df.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen              39.1             18.7              181.0   
1  Adelie  Torgersen              39.5             17.4              186.0   
2  Adelie  Torgersen              40.3             18.0              195.0   
3  Adelie  Torgersen               NaN              NaN                NaN   
4  Adelie  Torgersen              36.7             19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [ ]:
print((df['culmen_length_mm'].isnull()).sum())

2


In [ ]:
df = df[ -df['culmen_length_mm'].isnull() ]

In [ ]:
df.head()

species     island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen              39.1             18.7              181.0   
1  Adelie  Torgersen              39.5             17.4              186.0   
2  Adelie  Torgersen              40.3             18.0              195.0   
4  Adelie  Torgersen              36.7             19.3              193.0   
5  Adelie  Torgersen              39.3             20.6              190.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
4       3450.0  FEMALE  
5       3650.0    MALE

In [ ]:
df['sex'].isnull().sum()

8

In [ ]:
df['sex'].unique()

array(['MALE', 'FEMALE', nan, '.'], dtype=object)

In [ ]:
df = df[-df['sex'].isnull()]

In [ ]:
df['sex'].unique()

array(['MALE', 'FEMALE', '.'], dtype=object)

In [ ]:
(df['sex'] == '.').sum()

1

In [ ]:
df = df[ df['sex'] != '.' ]

In [ ]:
df['species'].unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [ ]:
df['Adelie'] = (df['species'] == 'Adelie')*1
df['Chinstrap'] = (df['species'] == 'Chinstrap')*1
df['Gentoo'] = (df['species'] == 'Gentoo')*1
df = df.drop(columns=['species'])

In [ ]:
df['island'].unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [ ]:
df['Torgersen'] = (df['island'] == 'Torgersen')*1
df['Biscoe'] = (df['island'] == 'Biscoe')*1
df['Dream'] = (df['island'] == 'Dream')*1
df = df.drop(columns=['island'])

In [ ]:
df['sex'].unique()

array(['MALE', 'FEMALE'], dtype=object)

In [ ]:
df['sex'] = df['sex'].replace(['MALE','FEMALE'],[0,1])

In [ ]:
df.head()

culmen_length_mm  culmen_depth_mm  flipper_length_mm  body_mass_g  sex  \
0              39.1             18.7              181.0       3750.0    0   
1              39.5             17.4              186.0       3800.0    1   
2              40.3             18.0              195.0       3250.0    1   
4              36.7             19.3              193.0       3450.0    1   
5              39.3             20.6              190.0       3650.0    0   

   Adelie  Chinstrap  Gentoo  Torgersen  Biscoe  Dream  
0       1          0       0          1       0      0  
1       1          0       0          1       0      0  
2       1          0       0          1       0      0  
4       1          0       0          1       0      0  
5       1          0       0          1       0      0

In [ ]:
X = df.drop(columns=['Adelie','Chinstrap','Gentoo']).to_numpy()
print(X)

[[ 39.1  18.7 181.  ...   1.    0.    0. ]
 [ 39.5  17.4 186.  ...   1.    0.    0. ]
 [ 40.3  18.  195.  ...   1.    0.    0. ]
 ...
 [ 50.4  15.7 222.  ...   0.    1.    0. ]
 [ 45.2  14.8 212.  ...   0.    1.    0. ]
 [ 49.9  16.1 213.  ...   0.    1.    0. ]]


In [ ]:
Y = df[['Adelie','Chinstrap','Gentoo']].to_numpy()

In [ ]:
Y[0,:]

array([1, 0, 0])

In [ ]:
X_train, X_val, Y_train, Y_val = train_test_split(X,Y,test_size=0.25,random_state=4)

In [ ]:
scaler = preprocessing.StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_val_scaled = scaler.transform(X_val)

In [ ]:
model = 0
model = Sequential()
#model.add(Dense(4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', metrics = ['accuracy'])
model.fit(X_train_scaled,Y_train,epochs = 200,verbose=0, validation_data = (X_val_scaled,Y_val))
J_list = model.history.history['loss']
plt.plot(J_list)
pd.DataFrame(model.history.history)


ValueError: ignored

In [ ]:
losses = pd.DataFrame(model.history.history)
losses

In [ ]:
X.shape

(333, 8)

In [ ]:
island = 'Torgersen'
culmen_length_mm = 40
culmen_depth_mm	= 20
flipper_length_mm	= 180
body_mass_g	= 3000
sex = 'MALE'

In [ ]:
d = {'island': [island], 'culmen_length_mm': [culmen_length_mm], 'culmen_depth_mm': [culmen_depth_mm], 'flipper_length_mm':[flipper_length_mm], 'body_mass_g':[body_mass_g],'sex':[sex]}
d_input = pd.DataFrame(data=d)

In [ ]:
d_input

island  culmen_length_mm  culmen_depth_mm  flipper_length_mm  \
0  Torgersen                40               20                180   

   body_mass_g   sex  
0         3000  MALE

In [ ]:
d = {'island': [island], 'culmen_length_mm': [culmen_length_mm], 'culmen_depth_mm': [culmen_depth_mm], 'flipper_length_mm':[flipper_length_mm], 'body_mass_g':[body_mass_g],'sex':[sex]}
d_input = pd.DataFrame(data=d)
d_input['Torgersen'] = (d_input['island'] == 'Torgersen')*1
d_input['Biscoe'] = (d_input['island'] == 'Biscoe')*1
d_input['Dream'] = (d_input['island'] == 'Dream')*1
d_input = d_input.drop(columns=['island'])
d_input['sex'] = d_input['sex'].replace(['MALE','FEMALE'],[0,1])
input = d_input.to_numpy()
input_scaled = scaler.transform(input)

In [ ]:
input_scaled

array([[-0.73612183,  1.53563264, -1.46703287, -1.4651526 , -1.02028604,
         2.51466288, -0.99599197, -0.75891328]])

In [ ]:
y_hat = model.predict(input_scaled)[0]

1/1 [==============================] - 0s 81ms/step


In [ ]:
y_hat

array([9.9993038e-01, 6.9548034e-05, 1.2326059e-07], dtype=float32)

In [ ]:
i = 0
for j in range(1,len(y_hat)):
  if y_hat[j] > y_hat[i]:
    i = j
i


0